import os
import pandas as pd
import matplotlib.pyplot as plt


def generate_executive_report(df, output_path='reports/executive_summary.md'):
    """Compiles analytical outcomes into a clean, scannable Markdown briefing."""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    
    # Isolating targets
    viable_markets = df[df['passed_constraints']].head(5)
    traps_identified = df[df['city'].str.contains('Trap', case=False)]
    gems_identified = df[df['city'].str.contains('Gem', case=False)]
    
    markdown_content = fr"""# Executive Briefing: Global Market Expansion Optimization
**Data Pipeline Status:** Production Ready  
**Analysis Framework:** Composite Risk/Velocity Optimization (Weights: 35% Sales, 35% GDP, 15% Inf, 15% Comp)

---

## Strategic Recommendation: Top 5 Expansion Targets
These territories cleared all strategic guardrails (CAC $\le$ $300, Inflation Risk < High) and offer the peak efficiency returns.

| Rank | City | Country | Historical Sales | Market Score | CAC |
| :--- | :--- | :--- | :--- | :--- | :--- |
{chr(10).join([f"| {i+1} | {row['city']} | {row['country']} | ${row['historical_sales_usd']:,.2f} | **{row['market_score']:.4f}** | ${row['customer_acquisition_cost_usd']:.2f} |" for i, row in viable_markets.iterrows()])}

---

## Pipeline Stress-Test: Archetype Validations

### 1. The High-Inflation Traps (High Volume / Exploding Macro Risk)
*Goal: The framework must flag and bypass these high-performing vanity revenue markets.*

| City | Historical Sales | Norm Inflation | Passed Constraints? | Market Score |
| :--- | :--- | :--- | :--- | :--- |
{chr(10).join([f"| {row['city']} | ${row['historical_sales_usd']:,.2f} | {row['norm_inflation']:.2f} | {row['passed_constraints']} | {row['market_score']:.4f} |" for _, row in traps_identified.iterrows()])}

### 2. The Hidden Gems (Moderate Volume / Low Competition / Stable Macro)
*Goal: Identify under-the-radar, high-efficiency expansion vectors.*

| City | Historical Sales | Norm Competition | CAC | Market Score |
| :--- | :--- | :--- | :--- | :--- |
{chr(10).join([f"| {row['city']} | ${row['historical_sales_usd']:,.2f} | {row['norm_competition']:.2f} | ${row['customer_acquisition_cost_usd']:.2f} | **{row['market_score']:.4f}** |" for _, row in gems_identified.iterrows()])}

---
*Report auto-generated by the Sales Optimization Engine.*
"""   
    
    with open(output_path, 'w') as f:
        f.write(markdown_content)
    print(f" Executive Markdown Report successfully exported to: {output_path}")


if __name__ == "__main__":
    results_df = run_market_optimization()
    generate_executive_report(results_df)

from IPython.display import display, Markdown

# Define the path to the report
report_path = 'reports/executive_summary.md'

# Read the file content
with open(report_path, 'r', encoding='utf-8') as file:
    markdown_content = file.read()

# Render it beautifully inside the notebook
display(Markdown(markdown_content))
